2022-04-26 12:44:52,386 - root - CRITICAL - Отсутствует 1156138850
2022-04-26 12:44:52,572 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-26 12:44:54,028 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1650966292 HTTP/1.1" 200 42
2022-04-26 12:44:54,033 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650966294}
2022-04-26 12:44:54,033 - telegram.bot - DEBUG - Entering: send_message
2022-04-26 12:44:57,341 - telegram.bot - DEBUG - {'caption_entities': [], 'chat': {'first_name': 'Aurora', 'type': 'private', 'id': 1156138850}, 'text': "Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650966294}", 'photo': [], 'message_id': 8, 'channel_chat_created': False, 'group_chat_created': False, 'entities': [], 'new_chat_members': [], 'new_chat_photo': [], 'date': 1650966297, 'supergroup_chat_created': False, 'delete_chat_photo': False, 'from': {'first_name': 'HomeworkYandexPracticumBot', 'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247, 'is_bot': True}}
2022-04-26 12:44:57,342 - telegram.bot - DEBUG - Exiting: send_message
2022-04-26 12:49:33,281 - root - CRITICAL - Отсутствует 1156138850
2022-04-26 12:49:33,294 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-26 12:49:34,315 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1650966573 HTTP/1.1" 200 42
2022-04-26 12:49:34,320 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650966574}
2022-04-26 12:49:34,320 - telegram.bot - DEBUG - Entering: send_message
2022-04-26 12:49:34,645 - telegram.bot - DEBUG - {'caption_entities': [], 'date': 1650966574, 'supergroup_chat_created': False, 'channel_chat_created': False, 'group_chat_created': False, 'message_id': 9, 'delete_chat_photo': False, 'new_chat_members': [], 'photo': [], 'text': "Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650966574}", 'chat': {'first_name': 'Aurora', 'id': 1156138850, 'type': 'private'}, 'entities': [], 'new_chat_photo': [], 'from': {'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot', 'is_bot': True}}
2022-04-26 12:49:34,646 - telegram.bot - DEBUG - Exiting: send_message
2022-04-26 12:51:05,350 - root - CRITICAL - Отсутствует 1156138850
2022-04-26 12:51:05,375 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-26 12:51:06,790 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1650966665 HTTP/1.1" 200 42
2022-04-26 12:51:06,795 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650966666}
2022-04-26 12:51:06,795 - telegram.bot - DEBUG - Entering: send_message
2022-04-26 12:51:07,103 - telegram.bot - DEBUG - {'supergroup_chat_created': False, 'group_chat_created': False, 'delete_chat_photo': False, 'new_chat_photo': [], 'chat': {'first_name': 'Aurora', 'type': 'private', 'id': 1156138850}, 'entities': [], 'channel_chat_created': False, 'photo': [], 'message_id': 10, 'caption_entities': [], 'text': "Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650966666}", 'new_chat_members': [], 'date': 1650966667, 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247}}
2022-04-26 12:51:07,104 - telegram.bot - DEBUG - Exiting: send_message
2022-04-26 13:01:07,091 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-26 13:01:08,087 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1650966666 HTTP/1.1" 200 42
2022-04-26 13:01:08,092 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650967268}
2022-04-26 13:01:08,092 - telegram.bot - DEBUG - Entering: send_message
2022-04-26 16:26:15,469 - root - CRITICAL - Отсутствует 1156138850
2022-04-26 16:26:15,600 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-26 16:26:16,597 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1650979575 HTTP/1.1" 200 42
2022-04-26 16:26:16,602 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650979576}
2022-04-26 16:26:16,602 - telegram.bot - DEBUG - Entering: send_message
2022-04-26 16:26:17,003 - telegram.bot - DEBUG - {'text': "Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650979576}", 'delete_chat_photo': False, 'group_chat_created': False, 'channel_chat_created': False, 'photo': [], 'new_chat_members': [], 'chat': {'first_name': 'Aurora', 'type': 'private', 'id': 1156138850}, 'date': 1650979577, 'message_id': 11, 'caption_entities': [], 'supergroup_chat_created': False, 'entities': [], 'new_chat_photo': [], 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'is_bot': True}}
2022-04-26 16:26:17,004 - telegram.bot - DEBUG - Exiting: send_message
2022-04-26 16:59:34,969 - root - CRITICAL - Отсутствует 1156138850
2022-04-26 16:59:34,983 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-26 16:59:36,176 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1650981574 HTTP/1.1" 200 42
2022-04-26 16:59:36,181 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650981576}
2022-04-26 16:59:36,181 - telegram.bot - DEBUG - Entering: send_message
2022-04-26 16:59:36,959 - telegram.bot - DEBUG - {'entities': [], 'new_chat_members': [], 'delete_chat_photo': False, 'caption_entities': [], 'group_chat_created': False, 'date': 1650981577, 'supergroup_chat_created': False, 'chat': {'id': 1156138850, 'type': 'private', 'first_name': 'Aurora'}, 'new_chat_photo': [], 'message_id': 12, 'photo': [], 'text': "Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650981576}", 'channel_chat_created': False, 'from': {'is_bot': True, 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot', 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-26 16:59:36,959 - telegram.bot - DEBUG - Exiting: send_message
2022-04-26 18:19:36,878 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-26 18:19:37,756 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1650981576 HTTP/1.1" 200 42
2022-04-26 18:19:37,759 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650986377}
2022-04-26 18:19:37,759 - telegram.bot - DEBUG - Entering: send_message
2022-04-26 18:40:55,773 - root - CRITICAL - Отсутствует 1156138850
2022-04-26 18:40:55,948 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-26 18:40:57,247 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1650987655 HTTP/1.1" 200 42
2022-04-26 18:40:57,252 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650987657}
2022-04-26 18:40:57,253 - telegram.bot - DEBUG - Entering: send_message
2022-04-26 18:40:58,168 - telegram.bot - DEBUG - {'entities': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'caption_entities': [], 'text': "Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1650987657}", 'message_id': 13, 'date': 1650987658, 'new_chat_photo': [], 'new_chat_members': [], 'group_chat_created': False, 'delete_chat_photo': False, 'photo': [], 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot', 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-26 18:40:58,169 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 00:11:24,809 - root - CRITICAL - Отсутствует 1156138850
2022-04-27 00:11:24,996 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 00:11:25,762 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651007484 HTTP/1.1" 200 42
2022-04-27 00:11:25,767 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651007485}
2022-04-27 00:11:25,767 - telegram.bot - DEBUG - Entering: send_message
2022-04-27 00:11:26,125 - telegram.bot - DEBUG - {'chat': {'first_name': 'Aurora', 'id': 1156138850, 'type': 'private'}, 'text': "Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651007485}", 'caption_entities': [], 'new_chat_photo': [], 'group_chat_created': False, 'message_id': 14, 'photo': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'new_chat_members': [], 'date': 1651007486, 'entities': [], 'supergroup_chat_created': False, 'from': {'first_name': 'HomeworkYandexPracticumBot', 'is_bot': True, 'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247}}
2022-04-27 00:11:26,126 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 12:46:42,826 - root - CRITICAL - Отсутствует 1156138850
2022-04-27 12:46:42,951 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 12:46:43,483 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651052802 HTTP/1.1" 200 42
2022-04-27 12:46:43,488 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651052803}
2022-04-27 12:46:43,488 - telegram.bot - DEBUG - Entering: send_message
2022-04-27 12:46:43,903 - telegram.bot - DEBUG - {'channel_chat_created': False, 'group_chat_created': False, 'chat': {'id': 1156138850, 'first_name': 'Aurora', 'type': 'private'}, 'new_chat_photo': [], 'photo': [], 'new_chat_members': [], 'delete_chat_photo': False, 'text': "Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651052803}", 'message_id': 15, 'caption_entities': [], 'entities': [], 'date': 1651052804, 'supergroup_chat_created': False, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247}}
2022-04-27 12:46:43,904 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 15:27:55,778 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 15:27:56,314 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651062475 HTTP/1.1" 200 42
2022-04-27 15:27:56,316 - __main__ - ERROR - Сбой в работе программы: Список пуст
2022-04-27 15:27:56,316 - telegram.bot - DEBUG - Entering: send_message
2022-04-27 15:27:56,648 - telegram.bot - DEBUG - {'chat': {'first_name': 'Aurora', 'type': 'private', 'id': 1156138850}, 'caption_entities': [], 'text': 'Сбой в работе программы: Список пуст', 'entities': [], 'message_id': 16, 'date': 1651062476, 'supergroup_chat_created': False, 'photo': [], 'group_chat_created': False, 'channel_chat_created': False, 'new_chat_photo': [], 'delete_chat_photo': False, 'new_chat_members': [], 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'is_bot': True}}
2022-04-27 15:27:56,649 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 16:02:21,311 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 16:02:21,853 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651064541 HTTP/1.1" 200 42
2022-04-27 16:02:21,858 - __main__ - ERROR - Сбой в работе программы: Список пуст
2022-04-27 16:02:21,859 - telegram.bot - DEBUG - Entering: send_message
2022-04-27 16:02:22,227 - telegram.bot - DEBUG - {'message_id': 17, 'delete_chat_photo': False, 'chat': {'type': 'private', 'id': 1156138850, 'first_name': 'Aurora'}, 'text': 'Сбой в работе программы: Список пуст', 'new_chat_photo': [], 'photo': [], 'supergroup_chat_created': False, 'new_chat_members': [], 'date': 1651064542, 'channel_chat_created': False, 'caption_entities': [], 'entities': [], 'group_chat_created': False, 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247}}
2022-04-27 16:02:22,227 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 16:12:22,201 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 16:12:22,865 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651065142 HTTP/1.1" 200 42
2022-04-27 16:12:22,877 - __main__ - ERROR - Сбой в работе программы: Список пуст
2022-04-27 16:12:22,877 - telegram.bot - DEBUG - Entering: send_message
2022-04-27 16:12:23,423 - telegram.bot - DEBUG - {'message_id': 18, 'delete_chat_photo': False, 'chat': {'type': 'private', 'id': 1156138850, 'first_name': 'Aurora'}, 'text': 'Сбой в работе программы: Список пуст', 'new_chat_photo': [], 'photo': [], 'supergroup_chat_created': False, 'new_chat_members': [], 'date': 1651065143, 'channel_chat_created': False, 'caption_entities': [], 'entities': [], 'group_chat_created': False, 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247}}
2022-04-27 16:12:23,426 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 16:31:30,098 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 16:31:31,086 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651066289 HTTP/1.1" 200 42
2022-04-27 16:31:31,092 - __main__ - ERROR - Сбой в работе программы: Список пуст
2022-04-27 16:31:31,092 - telegram.bot - DEBUG - Entering: send_message
2022-04-27 16:31:31,499 - telegram.bot - DEBUG - {'message_id': 19, 'supergroup_chat_created': False, 'photo': [], 'text': 'Сбой в работе программы: Список пуст', 'delete_chat_photo': False, 'new_chat_members': [], 'date': 1651066291, 'channel_chat_created': False, 'new_chat_photo': [], 'group_chat_created': False, 'entities': [], 'chat': {'type': 'private', 'id': 1156138850, 'first_name': 'Aurora'}, 'caption_entities': [], 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247, 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-27 16:31:31,499 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 16:54:42,146 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 16:54:43,418 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651067681 HTTP/1.1" 200 42
2022-04-27 16:54:43,424 - __main__ - ERROR - Сбой в работе программы: Список пуст
2022-04-27 16:54:43,424 - telegram.bot - DEBUG - Entering: send_message
2022-04-27 16:54:43,867 - telegram.bot - DEBUG - {'message_id': 20, 'delete_chat_photo': False, 'caption_entities': [], 'channel_chat_created': False, 'new_chat_photo': [], 'chat': {'first_name': 'Aurora', 'type': 'private', 'id': 1156138850}, 'text': 'Сбой в работе программы: Список пуст', 'new_chat_members': [], 'group_chat_created': False, 'supergroup_chat_created': False, 'entities': [], 'photo': [], 'date': 1651067684, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'is_bot': True}}
2022-04-27 16:54:43,868 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 17:20:22,103 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 17:20:23,351 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651069214 HTTP/1.1" 200 42
2022-04-27 17:20:23,357 - __main__ - ERROR - Сбой в работе программы: Список пуст
2022-04-27 17:20:23,357 - telegram.bot - DEBUG - Entering: send_message
2022-04-27 17:20:23,668 - telegram.bot - DEBUG - {'date': 1651069223, 'caption_entities': [], 'entities': [], 'delete_chat_photo': False, 'message_id': 21, 'photo': [], 'channel_chat_created': False, 'text': 'Сбой в работе программы: Список пуст', 'supergroup_chat_created': False, 'chat': {'type': 'private', 'id': 1156138850, 'first_name': 'Aurora'}, 'new_chat_photo': [], 'new_chat_members': [], 'group_chat_created': False, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'is_bot': True}}
2022-04-27 17:20:23,669 - telegram.bot - DEBUG - Exiting: send_message
2022-04-27 17:59:36,658 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 17:59:37,198 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651071576 HTTP/1.1" 200 42
2022-04-27 17:59:37,203 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651071577}
2022-04-27 18:25:55,748 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 18:25:56,295 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651073155 HTTP/1.1" 200 42
2022-04-27 18:25:56,301 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651073156}
2022-04-27 22:28:48,148 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 22:28:48,745 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651087728 HTTP/1.1" 200 42
2022-04-27 22:28:48,750 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651087728}
2022-04-27 22:32:53,595 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 22:32:54,252 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651087973 HTTP/1.1" 200 42
2022-04-27 22:32:54,258 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651087974}
2022-04-27 22:53:02,940 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 22:53:03,433 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651089182 HTTP/1.1" 200 42
2022-04-27 22:53:03,438 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651089183}
2022-04-27 23:08:47,939 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:08:48,491 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651090127 HTTP/1.1" 200 42
2022-04-27 23:08:48,496 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651090128}
2022-04-27 23:10:01,894 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:10:02,434 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651090201 HTTP/1.1" 200 42
2022-04-27 23:10:02,440 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651090202}
2022-04-27 23:11:30,240 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:11:30,919 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651090290 HTTP/1.1" 200 42
2022-04-27 23:11:30,924 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651090291}
2022-04-27 23:18:17,899 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:18:18,712 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651090697 HTTP/1.1" 200 42
2022-04-27 23:18:18,717 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651090698}
2022-04-27 23:18:42,147 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:18:42,691 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651090722 HTTP/1.1" 200 42
2022-04-27 23:18:42,696 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651090722}
2022-04-27 23:33:50,622 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:33:51,203 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651091630 HTTP/1.1" 200 42
2022-04-27 23:33:51,208 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651091631}
2022-04-27 23:34:57,369 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:34:57,852 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651091697 HTTP/1.1" 200 42
2022-04-27 23:34:57,857 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651091698}
2022-04-27 23:41:25,498 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:41:26,186 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651092085 HTTP/1.1" 200 42
2022-04-27 23:41:26,190 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651092086}
2022-04-27 23:43:28,422 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:43:29,146 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651092208 HTTP/1.1" 200 42
2022-04-27 23:43:29,151 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651092209}
2022-04-27 23:44:04,221 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:44:05,312 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651092244 HTTP/1.1" 200 42
2022-04-27 23:44:05,317 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651092244}
2022-04-27 23:44:35,579 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:44:36,111 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651092275 HTTP/1.1" 200 42
2022-04-27 23:44:36,116 - __main__ - ERROR - Сбой в работе программы: Отсутствуют данные в {'homeworks': [], 'current_date': 1651092276}
2022-04-27 23:55:27,155 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-27 23:55:27,976 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651092927 HTTP/1.1" 200 42
2022-04-28 00:02:20,881 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:02:21,382 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651093340 HTTP/1.1" 200 42
2022-04-28 00:20:27,520 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:20:28,033 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651094427 HTTP/1.1" 200 42
2022-04-28 00:21:41,703 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:21:42,201 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651094501 HTTP/1.1" 200 42
2022-04-28 00:23:32,616 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:23:33,212 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651094612 HTTP/1.1" 200 42
2022-04-28 00:25:42,746 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:25:43,239 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651094742 HTTP/1.1" 200 42
2022-04-28 00:25:55,448 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:25:56,133 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651094755 HTTP/1.1" 200 42
2022-04-28 00:36:16,196 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:36:16,813 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651095375 HTTP/1.1" 200 42
2022-04-28 00:40:04,601 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:40:09,276 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651095604 HTTP/1.1" 200 42
2022-04-28 00:40:09,281 - __main__ - ERROR - Сбой. Отсутствуют данные в {'homeworks': [], 'current_date': 1651095609}
2022-04-28 00:45:24,276 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 00:45:25,892 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651095924 HTTP/1.1" 200 42
2022-04-28 00:45:25,897 - __main__ - ERROR - Сбой. Отсутствуют данные в {'homeworks': [], 'current_date': 1651095925}
2022-04-28 01:16:26,278 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:16:26,887 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651097786 HTTP/1.1" 200 42
2022-04-28 01:16:26,893 - __main__ - ERROR - Сбой. Отсутствуют данные в {'homeworks': [], 'current_date': 1651097786}
2022-04-28 01:20:02,859 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:20:04,006 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651098002 HTTP/1.1" 200 42
2022-04-28 01:20:04,011 - __main__ - ERROR - Сбой. Отсутствуют данные в {'homeworks': [], 'current_date': 1651098004}
2022-04-28 01:21:56,826 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:21:57,321 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651098116 HTTP/1.1" 200 42
2022-04-28 01:21:57,326 - __main__ - ERROR - Сбой. Отсутствуют данные в {'homeworks': [], 'current_date': 1651098117}
2022-04-28 01:23:14,202 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:23:14,815 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651098194 HTTP/1.1" 200 42
2022-04-28 01:23:14,820 - __main__ - ERROR - Сбой. Отсутствуют данные в {'homeworks': [], 'current_date': 1651098194}
2022-04-28 01:27:08,106 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:27:08,971 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651098428 HTTP/1.1" 200 42
2022-04-28 01:27:08,976 - __main__ - ERROR - Сбой. Отсутствуют данные в {'homeworks': [], 'current_date': 1651098428}
2022-04-28 01:28:19,030 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:28:19,965 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651098499 HTTP/1.1" 200 42
2022-04-28 01:28:19,970 - __main__ - ERROR - Сбой. Отсутствуют данные в {'homeworks': [], 'current_date': 1651098499}
2022-04-28 01:37:00,053 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:37:00,603 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651099019 HTTP/1.1" 200 42
2022-04-28 01:37:00,608 - root - INFO - Статус обновлен
2022-04-28 01:37:00,608 - __main__ - ERROR - Сбой. Некорректный тип ответа
2022-04-28 01:41:14,222 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:41:14,807 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651099274 HTTP/1.1" 200 42
2022-04-28 01:41:14,812 - root - INFO - Статус обновлен
2022-04-28 01:41:14,813 - __main__ - ERROR - Сбой. Некорректный тип ответа
2022-04-28 01:41:41,936 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:41:42,546 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651099301 HTTP/1.1" 200 42
2022-04-28 01:41:42,551 - root - INFO - Статус обновлен
2022-04-28 01:41:42,551 - __main__ - ERROR - Сбой. 'Отсутствуют искомые ключи'
2022-04-28 01:52:53,013 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 01:52:53,693 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651099972 HTTP/1.1" 200 42
2022-04-28 01:52:53,698 - root - INFO - Статус обновлен
2022-04-28 01:52:53,698 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 02:00:50,976 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 02:00:51,501 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648508450 HTTP/1.1" 200 767
2022-04-28 02:00:51,507 - root - INFO - Статус обновлен
2022-04-28 02:00:51,507 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 02:03:09,028 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 02:03:10,232 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651100589 HTTP/1.1" 200 42
2022-04-28 02:03:10,237 - root - INFO - Статус обновлен
2022-04-28 02:03:10,237 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 02:03:51,490 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 02:03:52,081 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651100631 HTTP/1.1" 200 42
2022-04-28 02:03:52,086 - root - INFO - Статус обновлен
2022-04-28 02:03:52,086 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 02:07:03,924 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 02:07:04,473 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651100823 HTTP/1.1" 200 42
2022-04-28 02:07:04,478 - root - INFO - Статус обновлен
2022-04-28 02:07:04,478 - __main__ - ERROR - Сбой. Некорректный тип ответа
2022-04-28 02:08:39,942 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 02:08:40,541 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651100919 HTTP/1.1" 200 42
2022-04-28 02:08:40,546 - root - INFO - Статус обновлен
2022-04-28 02:08:40,546 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 02:10:03,475 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 02:10:04,066 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651101003 HTTP/1.1" 200 42
2022-04-28 02:10:04,071 - root - INFO - Статус обновлен
2022-04-28 02:10:04,071 - __main__ - ERROR - Сбой. Некорректный тип ответа
2022-04-28 11:12:37,465 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:12:37,468 - __main__ - ERROR - Сбой. Запрос к API не выполнен.
2022-04-28 11:12:37,468 - __main__ - ERROR - Сбой. local variable 'response' referenced before assignment
2022-04-28 11:15:08,746 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:15:10,238 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651133708 HTTP/1.1" 200 42
2022-04-28 11:15:10,244 - root - INFO - Статус обновлен
2022-04-28 11:15:10,244 - __main__ - ERROR - Сбой. Некорректный тип ответа
2022-04-28 11:19:01,991 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:19:02,623 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651133935 HTTP/1.1" 200 42
2022-04-28 11:19:07,939 - root - INFO - Статус обновлен
2022-04-28 11:20:03,946 - __main__ - ERROR - Сбой. Некорректный тип ответа
2022-04-28 11:20:53,943 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:20:54,548 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651134044 HTTP/1.1" 200 42
2022-04-28 11:22:35,202 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:22:36,003 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651134155 HTTP/1.1" 200 42
2022-04-28 11:22:36,008 - root - INFO - Статус обновлен
2022-04-28 11:22:36,008 - __main__ - ERROR - Сбой. argument of type 'NoneType' is not iterable
2022-04-28 11:23:24,310 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:23:24,978 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651134204 HTTP/1.1" 200 42
2022-04-28 11:23:24,984 - root - INFO - Статус обновлен
2022-04-28 11:23:24,984 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 11:26:58,294 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:26:58,828 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651134418 HTTP/1.1" 200 42
2022-04-28 11:26:58,833 - root - INFO - Статус обновлен
2022-04-28 11:26:58,833 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 11:28:55,004 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:28:55,673 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651134534 HTTP/1.1" 200 42
2022-04-28 11:28:55,677 - root - INFO - Статус обновлен
2022-04-28 11:28:55,677 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 11:41:44,988 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:41:45,482 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651135304 HTTP/1.1" 200 42
2022-04-28 11:41:45,487 - root - INFO - Статус обновлен
2022-04-28 11:41:45,487 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 11:45:02,658 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:45:03,201 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651135502 HTTP/1.1" 200 42
2022-04-28 11:45:03,205 - root - INFO - Статус обновлен
2022-04-28 11:45:03,205 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 11:50:02,007 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:50:02,520 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651135801 HTTP/1.1" 200 42
2022-04-28 11:50:02,525 - root - INFO - Статус обновлен
2022-04-28 11:50:02,525 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 11:51:08,435 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:51:09,233 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651135868 HTTP/1.1" 200 42
2022-04-28 11:51:09,239 - root - INFO - Статус обновлен
2022-04-28 11:51:09,240 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 11:55:23,625 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:55:24,139 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651136123 HTTP/1.1" 200 42
2022-04-28 11:55:24,144 - root - INFO - Статус обновлен
2022-04-28 11:55:24,145 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 11:56:07,494 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:56:08,002 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651136167 HTTP/1.1" 200 42
2022-04-28 11:56:08,006 - root - INFO - Статус обновлен
2022-04-28 11:56:08,007 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 11:57:28,749 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:57:29,469 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=0 HTTP/1.1" 200 None
2022-04-28 11:57:29,478 - root - INFO - Статус обновлен
2022-04-28 11:58:20,218 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 11:58:20,856 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651136300 HTTP/1.1" 200 42
2022-04-28 11:58:20,861 - root - INFO - Статус обновлен
2022-04-28 11:58:20,862 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:08:56,702 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:08:57,226 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651136936 HTTP/1.1" 200 42
2022-04-28 12:08:57,231 - root - INFO - Статус обновлен
2022-04-28 12:08:57,231 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:13:34,238 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:13:34,739 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651137214 HTTP/1.1" 200 42
2022-04-28 12:13:34,745 - root - INFO - Статус обновлен
2022-04-28 12:13:34,745 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:21:41,464 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:21:42,188 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651137701 HTTP/1.1" 200 42
2022-04-28 12:21:42,193 - root - INFO - Статус обновлен
2022-04-28 12:21:42,193 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:26:20,340 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:26:20,897 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651137980 HTTP/1.1" 200 42
2022-04-28 12:26:20,901 - root - INFO - Статус обновлен
2022-04-28 12:26:20,902 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:34:52,691 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:34:53,269 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651138492 HTTP/1.1" 200 42
2022-04-28 12:34:53,274 - root - INFO - Статус обновлен
2022-04-28 12:34:53,274 - root - INFO - Статус не обновлен
2022-04-28 12:34:53,274 - __main__ - ERROR - Сбой. 'list' object has no attribute 'get'
2022-04-28 12:36:42,011 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:36:42,560 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651138601 HTTP/1.1" 200 42
2022-04-28 12:36:42,566 - root - INFO - Статус обновлен
2022-04-28 12:36:42,566 - root - INFO - Статус не обновлен
2022-04-28 12:36:42,566 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:38:05,283 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:38:13,262 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651138685 HTTP/1.1" 200 42
2022-04-28 12:38:13,268 - root - INFO - Статус обновлен
2022-04-28 12:38:13,268 - __main__ - ERROR - Сбой. Статус не обновлен
2022-04-28 12:43:43,891 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:43:44,458 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547023 HTTP/1.1" 200 767
2022-04-28 12:43:44,464 - root - INFO - Статус обновлен
2022-04-28 12:43:44,464 - __main__ - ERROR - Сбой. 'Отсутствуют искомый ключ homework_name'
2022-04-28 12:44:44,225 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:44:44,816 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547084 HTTP/1.1" 200 767
2022-04-28 12:44:44,820 - root - INFO - Статус обновлен
2022-04-28 12:49:44,978 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:49:45,503 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651139384 HTTP/1.1" 200 42
2022-04-28 12:49:45,508 - root - INFO - Статус обновлен
2022-04-28 12:49:45,509 - root - INFO - Статус НЕ обновлен
2022-04-28 12:49:45,509 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:50:38,396 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:50:38,905 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547438 HTTP/1.1" 200 767
2022-04-28 12:50:38,910 - root - INFO - Статус обновлен
2022-04-28 12:52:07,519 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:52:08,065 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651139527 HTTP/1.1" 200 42
2022-04-28 12:52:08,071 - root - INFO - Статус обновлен
2022-04-28 12:52:08,071 - root - INFO - Статус НЕ обновлен
2022-04-28 12:52:08,071 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:52:51,320 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:52:51,912 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547571 HTTP/1.1" 200 767
2022-04-28 12:52:51,920 - root - INFO - Статус обновлен
2022-04-28 12:54:00,651 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:54:01,208 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547640 HTTP/1.1" 200 767
2022-04-28 12:54:01,216 - root - INFO - Статус обновлен
2022-04-28 12:54:44,889 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:54:45,457 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547684 HTTP/1.1" 200 767
2022-04-28 12:54:45,466 - root - INFO - Статус обновлен
2022-04-28 12:54:55,469 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:54:55,962 - telegram.bot - DEBUG - {'entities': [], 'message_id': 23, 'photo': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'date': 1651139696, 'group_chat_created': False, 'new_chat_photo': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'caption_entities': [], 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot'}}
2022-04-28 12:54:55,964 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:54:56,013 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:54:56,599 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547695 HTTP/1.1" 200 767
2022-04-28 12:54:56,612 - root - INFO - Статус обновлен
2022-04-28 12:55:06,615 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:55:06,980 - telegram.bot - DEBUG - {'entities': [], 'message_id': 24, 'photo': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'date': 1651139707, 'group_chat_created': False, 'new_chat_photo': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'caption_entities': [], 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot'}}
2022-04-28 12:55:06,981 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:55:07,014 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:55:07,747 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547706 HTTP/1.1" 200 767
2022-04-28 12:55:07,759 - root - INFO - Статус обновлен
2022-04-28 12:55:17,764 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:55:18,740 - telegram.bot - DEBUG - {'entities': [], 'message_id': 25, 'photo': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'date': 1651139718, 'group_chat_created': False, 'new_chat_photo': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'caption_entities': [], 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot'}}
2022-04-28 12:55:18,743 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:55:18,824 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:55:19,653 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547718 HTTP/1.1" 200 767
2022-04-28 12:55:19,673 - root - INFO - Статус обновлен
2022-04-28 12:55:29,682 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:55:29,990 - telegram.bot - DEBUG - {'entities': [], 'message_id': 26, 'photo': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'date': 1651139730, 'group_chat_created': False, 'new_chat_photo': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'caption_entities': [], 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot'}}
2022-04-28 12:55:29,991 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:55:30,008 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:55:30,616 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547729 HTTP/1.1" 200 767
2022-04-28 12:55:30,627 - root - INFO - Статус обновлен
2022-04-28 12:55:40,629 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:55:41,002 - telegram.bot - DEBUG - {'entities': [], 'message_id': 27, 'photo': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'date': 1651139741, 'group_chat_created': False, 'new_chat_photo': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'caption_entities': [], 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot'}}
2022-04-28 12:55:41,003 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:55:41,038 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:55:41,580 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547741 HTTP/1.1" 200 767
2022-04-28 12:55:41,589 - root - INFO - Статус обновлен
2022-04-28 12:55:51,592 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:55:52,024 - telegram.bot - DEBUG - {'entities': [], 'message_id': 28, 'photo': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'date': 1651139752, 'group_chat_created': False, 'new_chat_photo': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'caption_entities': [], 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot'}}
2022-04-28 12:55:52,025 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:55:52,051 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:55:52,906 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547752 HTTP/1.1" 200 767
2022-04-28 12:55:52,921 - root - INFO - Статус обновлен
2022-04-28 12:56:02,938 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:56:03,334 - telegram.bot - DEBUG - {'entities': [], 'message_id': 29, 'photo': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'date': 1651139763, 'group_chat_created': False, 'new_chat_photo': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'caption_entities': [], 'from': {'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot', 'id': 5300973247, 'username': 'Homework_Yandex_Practicum_Bot'}}
2022-04-28 12:56:03,337 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:56:03,375 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:56:04,287 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547763 HTTP/1.1" 200 767
2022-04-28 12:56:04,296 - root - INFO - Статус обновлен
2022-04-28 12:56:12,328 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:56:13,134 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651139772 HTTP/1.1" 200 42
2022-04-28 12:56:13,142 - root - INFO - Статус обновлен
2022-04-28 12:56:13,142 - root - INFO - Статус НЕ обновлен
2022-04-28 12:56:13,143 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:56:55,280 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:56:55,935 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651139815 HTTP/1.1" 200 42
2022-04-28 12:56:55,943 - root - INFO - Статус обновлен
2022-04-28 12:56:55,943 - root - INFO - Статус НЕ обновлен
2022-04-28 12:56:55,944 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:57:57,384 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:57:59,466 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651139877 HTTP/1.1" 200 42
2022-04-28 12:57:59,474 - root - INFO - Статус обновлен
2022-04-28 12:57:59,474 - root - INFO - Статус НЕ обновлен
2022-04-28 12:57:59,474 - __main__ - ERROR - Сбой. list index out of range
2022-04-28 12:58:27,256 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:58:27,783 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547907 HTTP/1.1" 200 767
2022-04-28 12:58:27,793 - root - INFO - Статус обновлен
2022-04-28 12:58:37,797 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:58:38,091 - telegram.bot - DEBUG - {'caption_entities': [], 'new_chat_photo': [], 'photo': [], 'supergroup_chat_created': False, 'date': 1651139918, 'new_chat_members': [], 'channel_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'message_id': 30, 'group_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247, 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-28 12:58:38,092 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:58:38,120 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:58:38,656 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547918 HTTP/1.1" 200 767
2022-04-28 12:58:38,664 - root - INFO - Статус обновлен
2022-04-28 12:58:48,670 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:58:48,991 - telegram.bot - DEBUG - {'caption_entities': [], 'new_chat_photo': [], 'photo': [], 'supergroup_chat_created': False, 'date': 1651139929, 'new_chat_members': [], 'channel_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'message_id': 31, 'group_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247, 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-28 12:58:48,992 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:58:49,029 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:58:49,656 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547929 HTTP/1.1" 200 767
2022-04-28 12:58:49,663 - root - INFO - Статус обновлен
2022-04-28 12:58:59,668 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:58:59,950 - telegram.bot - DEBUG - {'caption_entities': [], 'new_chat_photo': [], 'photo': [], 'supergroup_chat_created': False, 'date': 1651139940, 'new_chat_members': [], 'channel_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'message_id': 32, 'group_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247, 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-28 12:58:59,951 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:58:59,983 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:59:00,570 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547939 HTTP/1.1" 200 767
2022-04-28 12:59:00,577 - root - INFO - Статус обновлен
2022-04-28 12:59:10,582 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:59:10,909 - telegram.bot - DEBUG - {'caption_entities': [], 'new_chat_photo': [], 'photo': [], 'supergroup_chat_created': False, 'date': 1651139950, 'new_chat_members': [], 'channel_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'message_id': 33, 'group_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247, 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-28 12:59:10,910 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:59:10,931 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:59:11,543 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547950 HTTP/1.1" 200 767
2022-04-28 12:59:11,551 - root - INFO - Статус обновлен
2022-04-28 12:59:21,557 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:59:22,263 - telegram.bot - DEBUG - {'caption_entities': [], 'new_chat_photo': [], 'photo': [], 'supergroup_chat_created': False, 'date': 1651139962, 'new_chat_members': [], 'channel_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'message_id': 34, 'group_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247, 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-28 12:59:22,264 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:59:22,285 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:59:22,970 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547962 HTTP/1.1" 200 767
2022-04-28 12:59:22,982 - root - INFO - Статус обновлен
2022-04-28 12:59:32,994 - telegram.bot - DEBUG - Entering: send_message
2022-04-28 12:59:35,913 - telegram.bot - DEBUG - {'caption_entities': [], 'new_chat_photo': [], 'photo': [], 'supergroup_chat_created': False, 'date': 1651139975, 'new_chat_members': [], 'channel_chat_created': False, 'text': 'Изменился статус проверки работы "awrora2__homework_bot.zip". Работа проверена: у ревьюера есть замечания.', 'message_id': 35, 'group_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'chat': {'type': 'private', 'first_name': 'Aurora', 'id': 1156138850}, 'from': {'username': 'Homework_Yandex_Practicum_Bot', 'id': 5300973247, 'is_bot': True, 'first_name': 'HomeworkYandexPracticumBot'}}
2022-04-28 12:59:35,916 - telegram.bot - DEBUG - Exiting: send_message
2022-04-28 12:59:35,956 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 12:59:36,892 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648547975 HTTP/1.1" 200 767
2022-04-28 12:59:36,899 - root - INFO - Статус обновлен
2022-04-28 13:02:42,360 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 13:02:42,974 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1648548162 HTTP/1.1" 200 767
2022-04-28 13:02:42,984 - root - INFO - Статус обновлен
2022-04-28 13:39:11,036 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 13:39:11,781 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651142351 HTTP/1.1" 401 134
2022-04-28 13:39:11,786 - __main__ - ERROR - Сбой. API возвращает код, отличный от 200
2022-04-28 13:43:34,819 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): practicum.yandex.ru:443
2022-04-28 13:43:35,334 - urllib3.connectionpool - DEBUG - https://practicum.yandex.ru:443 "GET /api/user_api/homework_statuses/?from_date=1651142614 HTTP/1.1" 200 42
2022-04-28 13:43:35,339 - root - INFO - Статус обновлен
2022-04-28 13:43:35,339 - root - INFO - Статус не изменился
2022-04-28 13:43:35,339 - __main__ - ERROR - Сбой. list index out of range
